SlnErp102.Mvc/Models/ErrorViewModel.cs
namespace SlnErp102.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SlnErp102.Mvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SlnErp102.Mvc.Models;
using System.Diagnostics;

namespace SlnErp102.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SlnErp102.Mvc/Controllers/ProductEntryApiController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using SlnErp102.Api.DTOs.Stocks.Products;
using SlnErp102.Core.Models.Stocks.Products;
using SlnErp102.Mvc.ApiService.Stocks.Products;

namespace SlnErp102.Mvc.Controllers
{
    public class ProductEntryApiController : Controller
    {
        private readonly ProductEntryApiService _productEntryApiService;
        private readonly CompanyApiService _companyApiService;
        private readonly ProductEntryDto _productEntryDto;
        private readonly IMapper _mapper;


        public ProductEntryApiController(ProductEntryApiService productEntryApiService, IMapper mapper, CompanyApiService companyApiService, ProductEntryDto productEntryDto)
        {
            _productEntryApiService = productEntryApiService;
            _companyApiService = companyApiService;
            _productEntryDto = productEntryDto;
            _mapper = mapper;
        }


        public async Task<IActionResult> Index()
        {
            var productEnrty = await _productEntryApiService.GetAllAsync();
            return View(_mapper.Map<IEnumerable<ProductEntryDistinctDto>>(productEnrty));
        }

        [HttpGet]
        public JsonResult getProductCode()
        {
            //List<ProductDto> product = new List<ProductDto>();

            var proCode = _productEntryApiService.Products().Result;

            return Json(proCode);
            //return new JsonResult { Data = proCode, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public async Task<IActionResult> Details(string ivno)
        {
            var pEntry = await _productEntryApiService.GetProEntryByIvnoAsync(ivno);
            return View(_mapper.Map<IEnumerable<ProductEntryDto>>(pEntry));
        }

        public async Task<IActionResult> Create()
        {
            //getProductCode();
            List<SelectListItem> listCompany = new List<SelectListItem>();
            var CompanyItem = new SelectListItem()
            {
                Value = "",
                Text = "Select Company"
            };
            listCompany.Insert(0, CompanyItem);
            List<SelectListItem> CompanyItemList = (from s in _companyApiService.GetAllAsync().Result
                                                    select new SelectListItem()
                                                    {
                                                        Text = s.Name,
                                                        Value = s.Id.ToString()
                                                    }).ToList();
            listCompany.AddRange(CompanyItemList);
            TempData["Company"] = JsonConvert.SerializeObject(listCompany); //hata burda çözüldü ama tam anlamadım
            ViewBag.Company = listCompany;


            List<SelectListItem> listEntryType = new List<SelectListItem>();
            listEntryType.Insert(0, new SelectListItem()
            {
                Value = "",
                Text = "Select Entry Type"
            });
            var EntryTypeItem = new SelectListItem()
            {
                Value = 1.ToString(),
                Text = "Normal"
            };
            listEntryType.Add(EntryTypeItem);
            EntryTypeItem = new SelectListItem()
            {
                Value = 2.ToString(),
                Text = "Muhtelif"
            };
            listEntryType.Add(EntryTypeItem);
            TempData["EntryType"] = JsonConvert.SerializeObject(listEntryType);
            ViewBag.EntryType = listEntryType;

            return View();
        }

        [HttpPost]
        public IActionResult Create([FromBody] int id, string productCode)
        {

            return RedirectToAction("Index");
        }
        [HttpPost]
        public JsonResult save([FromBody]ProductPostUpDto postData)
        {
            if (postData.CompanyId>0)
            {

                //foreach (var item in postData.Products)
                //{
                //    _productEntryDto.EntryDate = postData.EntryDate;
                //    _productEntryDto.CompanyId = postData.CompanyId;
                //    _productEntryDto.InvoiceNumber = postData.InvoiceNumber;
                //    _productEntryDto.EntryTypeId = postData.EntryTypeId;
                //    _productEntryDto.Description = postData.Description;
                //    _productEntryDto.CompanyName = postData.CompanyName;
                //    _productEntryDto.LotSerial = item.LotSerial;
                //    _productEntryDto.ProductId = item.ProductId;
                //    _productEntryDto.Quantity = item.Quantity;
                //    _productEntryDto.ProductionDate = item.ProductionDate;
                //    _productEntryDto.Barcode = item.Barcode;
                //    _productEntryDto.ProductProductCode = item.ProductCode;
                //    _productEntryDto.ExpirationDate = item.ExpirationDate;
                //    var pro = _productEntryApiService.AddAsync(_productEntryDto).Result;
                //}

                //return Json(data=="True");
                return Json(new { status = "true"});
            }

            return Json(new { status = "false" }); 
        }
    }
}

SlnErp102.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SlnErp102.Mvc/Views/ProductEntryApi/Create.cshtml
@model SlnErp102.Api.DTOs.Stocks.Products.ProductEntryDto
@{

    ViewData["Title"] = "Create";
}
<div class="col-12 mx-auto pt-0 p-0">
    <div class="card">
        <div class="card-header bg-primary text-uppercase text-white" style="height:45px;">
            <h4>Create Invoice</h4>
        </div>
        <form id="Form" name="productForm" enctype="multipart/form-data" asp-action="Create">
            <div class="container-fluid btn-group p-3">
                <div class="col-12">
                    <div class="row">
                        <div asp-validation-summary=" ModelOnly" class="text-danger"></div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CompanyName" class="form-label"></label>
                                <select asp-for="CompanyName"  name="CompanyName" class="form-control" asp-items="ViewBag.Company"></select>
                                <span asp-validation-for="CompanyName" class=text-danger></span>
                            </div>
                        </div>

                        @*<div class="col-md-6">
                            <div asp-validation-summary=" ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                            <label asp-for="CompanyBranchName" class="control-label"></label>
                            <select asp-for="CompanyBranchName" class="form-label" asp-items="ViewBag.CompanyBranchName"></select>
                            <span asp-validation-for="CompanyBranchName" class=text-danger></span>
                            </div>
                            </div>*@

                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="InvoiceNumber" class="form-label" value="Invoice Number"></label>
                                <input asp-for="InvoiceNumber" name="InvoiceNumber" class="form-control" />
                                <span asp-validation-for="InvoiceNumber" class=text-danger></span>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="EntryDate" class="form-label" value="Entry Date"></label>
                                <input asp-for="EntryDate" name="EntryDate" class="form-control" type="date" />
                                <span asp-validation-for="InvoiceNumber" class=text-danger></span>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="EntryTypeId" class="form-label" value="Entry Type"></label>
                                <select asp-for="EntryTypeId" name="EntryTypeId" class="form-control" asp-items="ViewBag.EntryType"></select>
                                <span asp-validation-for="EntryTypeId" class=text-danger></span>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="form-label" value="Description"></label>
                                <input asp-for="Description" name="Description" class="form-control" />
                                <span asp-validation-for="Description" class=text-danger></span>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="container col-12">
                <div class="col-md-12" bg-light style="height:200px;overflow-y:auto">
                    <table id="Table" class="table table-sm CodesTable">
                        <thead>
                            <tr>
                                <th>Product Code</th>
                                <th>Lot Serial Number</th>
                                <th>Quantity</th>
                                <th>Production Date</th>
                                <th>DateExpiration Date</th>
                                <th>
                                    <button id='btnaddExperience' type="button" class="btn btn-sm btn-secondary visible"
                                            onclick="AddItem(this)">
                                        Add
                                    </button>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    @*<input asp-for="ProductProductCode" class="form-control"/>*@
                                    <select id="product" class="form-control">
                                        <option>Select</option>
                                    </select>
                                    <span class="error">Select product</span>
                                </td>
                                <td><input asp-for="LotSerial" class="form-control" /></td>
                                <td><input asp-for="Quantity" class="form-control" /></td>
                                <td><input asp-for="ProductionDate" class="form-control" /></td>
                                <td><input asp-for="ExpirationDate" class="form-control" /></td>
                                <td>
                                    <button id='btnremove' type="button" class="btn btn-sm btn-danger visible"
                                            onclick="DeleteItem(this)">
                                        Delete
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <input type="hidden" id="hdnLastIndex" value="0" />

                <div class="col-12 btn-group">
                    <div class="col-6 form-group text-right p-2">
                        <a asp-action="Index" class="btn btn-secondary">&nbsp;Back&nbsp;</a>
                        <input id="submit" type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<style>
    span.error {
        display: block;
        visibility: hidden;
        color: red;
        font-size: 90%;
    }

    tr.error {
        background-color: rgba(255,0,0,0.35);
    }
</style>

@section Scripts {
	@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
    
    <script type="text/javascript">
        var ProCode = [];

        function LoadProduct(element) {
            if (ProCode.length == 0) {
                //ajax function for fetch data
                $.ajax({
                    type: "GET",
                    url: '/ProductEntryApi/getProductCode',
                    success: function(data) {
                        ProCode = data;
                        //render product
                        renderProCode(element);
                    }
                });
            }
            else {
                //render catagory to the element
                renderProCode(element);
            }
        }


        function renderProCode(element) {
            var $ele = $(element);
            $ele.empty();
            $ele.append($('<option/>').val('0').text('Select'));
            $.each(ProCode,
                function(i, val) {
                    $ele.append($('<option/>').val(val.id).text(val.productCode));
                });

        }
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });



        function DeleteItem(btn) {
            var table=document.getElementById('Table');
            var rows = table.getElementsByTagName('tr');
            if(rows.length===2){
                alert("This row cannot be deleted");
                return;
            }
            $(btn).closest('tr').remove();
        }




        $( "#Form" ).submit(function( event ) {
             event.preventDefault();
              var table = document.getElementById('Table');
              var rows = table.getElementsByTagName('tr');


              var products=[];

             //Birden fazla satır içerisinden productları çektik ve diziye attık.
                for (let i = 1; i < rows.length; i++){

                    let rowContents = rows[i].getElementsByTagName('td');
                    let col1= $(rowContents[0]).find('select').val();
                    let col6= $(rowContents[0]).find('select').children(':selected').text();
                    let col2 =$(rowContents[1]).find('input').val();
                    let col3 =$(rowContents[2]).find('input').val();
                    let col4 =$(rowContents[3]).find('input').val();
                    let col5 =$(rowContents[4]).find('input').val();
                    console.log('ProCodeKontrol' + col6);
                    let data=
                    {
                        ProductId:col1,
                        ProductCode:col6,
                        LotSerial:col2,
                        Quantity:col3,
                        ProductionDate:col4,
                        ExpirationDate:col5,
                        Barcode:col6+'/'+col2

                    }
                    products.push(data);
                }
            //Form isminden verileri çektik ve içeirisne productları liste olarak gömdük.
              var postData={
                CompanyId:productForm.CompanyName.value,
                CompanyName:$('select[name="CompanyName"]').children(':selected').text(),
                InvoiceNumber:productForm.InvoiceNumber.value,
                EntryDate:productForm.EntryDate.value,
                EntryTypeId:productForm.EntryTypeId.value,
                Description:productForm.Description.value,
                Products:products
              };
              console.log(postData);
           $.ajax({
                type: "POST",
                url: "https://localhost:7063/ProductEntryApi/save",
                headers:{
                    'Content-Type': 'application/json',
                    'Accept':'application/json'
                },
                body: JSON.stringify(postData),
                data:JSON.stringify(postData),
                success: function(data){
                    if (data.status) {
                        alert('Successfully saved');
                        window.location.href = "https://localhost:7063/ProductEntryApi";
                        
                        //here we will clear the form
                        //list = [];
                        //$('#orderNo,#orderDate,#description').val('');
                        //$('#orderdetailsItems').empty();
                    }
                    else {
                        alert('Error ic');
                    }
                    $('#submit').text('Save');
                    console.log("başardık.");
                },
                error: function (error) {
                    console.log(error);
                    $('#submit').text('Save');
                }
            });


             });

        function AddItem(btn) {

            var table = document.getElementById('Table');
            var rows = table.getElementsByTagName('tr');


            var rowOuterHtml = rows[rows.length - 1].outerHTML;

            var lastrowIdx = rows.length-1;

            var nextrowIdx = eval(lastrowIdx);

            rowOuterHtml = rowOuterHtml.replaceAll('_' + lastrowIdx + '_', '_' + nextrowIdx + '_');
            rowOuterHtml = rowOuterHtml.replaceAll('[' + lastrowIdx + ']', '[' + nextrowIdx + ']');
            rowOuterHtml = rowOuterHtml.replaceAll('-' + lastrowIdx, '-' + nextrowIdx);

            var newRow = table.insertRow();
            newRow.innerHTML = rowOuterHtml;
        }


        LoadProduct($('#product'));
</script>
    
}

SlnErp102.Mvc/Views/ProductEntryApi/Details.cshtml
@model IEnumerable<ProductEntryDto>

@{
    ViewData["Title"] = "Details";
}
@foreach (var item in Model)
{
    <input type="text" readonly="true" value="@item.CompanyName"/>
    <input type="text" readonly="true" value="@item.EntryDate.ToShortDateString()"/>
    <input type="text" readonly="true" value="@item.InvoiceNumber"/>
                                                break;
}

<a class="btn btn-primary mb-2 col-md-2 btn-sm" asp-action="Create">Product Adding</a>
<table id="example" class="display" style="width:100%">
    <thead>
    <tr>
        @*<th>Id</th>*@
        @*<th>Company Id</th>*@
        <th>Urun Kodu</th>
        <th>Lot Serial No</th>
        @*<th>Barcode</th>*@
        @*<th>Entry Date</th>*@
        @*<th>Company Name</th>*@
        @*<th>Invoice Number</th>*@
        <th>Description</th>
        <th>Quantity</th>
        <th>Production Date</th>
        <th>Expiration Date</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            @*<th class="col-md-1">@item.Id</th>*@
            @*<th class="col-md-1">@item.CompanyId</th>*@
            <th class="col-md-1">@item.ProductProductCode</th>
            <th class="col-md-1">@item.LotSerial</th>
            @*<th class="col-md-2">@item.Barcode</th>*@
            @*<th class="col-md-2">@item.EntryDate</th>
            <th class="col-md-3">@item.CompanyName</th>
            <th class="col-md-1">@item.InvoiceNumber</th>*@
            <th class="col-md-3">@item.Description</th>
            <th class="col-md-1">@item.Quantity</th>
            <th class="col-md-2">@item.ProductionDate.ToShortDateString()</th>
            <th class="col-md-2">@item.ExpirationDate.ToShortDateString()</th>
            
        </tr>
    }
    </tbody>
</table>
<a class="btn btn-secondary btn-sm" asp-action="Index">Geri Dön</a>

SlnErp102.Mvc/Views/ProductEntryApi/Index.cshtml
@model IEnumerable<ProductEntryDistinctDto>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<a class="btn btn-primary mb-4 col-md-2" asp-action="Create">Product Adding</a>
<table id="example" class="display" style="width:100%">
    <thead>
    <tr>
        @*<th>Id</th>*@
        @*<th>Company Id</th>*@
        <th>Company Name</th>
        <th>Entry Date</th>
        <th>Invoice Number</th>
        <th>Islemler</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            @*<td class="col-md-1">@item.Id</td>*@
            @*<td class="col-md-1">@item..CompanyId</td>*@
            <td class="col-md-3">@item.CompanyName</td>
            <td class="col-md-3">@item.EntryDate.ToShortDateString()</td>
            <td class="col-md-2">@item.InvoiceNumber</td>
            <td class="col-md-2">
                <a class="btn btn-info btn-sm" asp-action="Details" asp-route-ivno="@item.InvoiceNumber">Details</a>
                <a class="btn btn-warning btn-sm" asp-action="Update" asp-route-id="@item.Id">Update</a>
                <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

SlnErp102.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SlnErp102.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SlnErp102.Mvc.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SlnErp102.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductEntryApi" asp-action="Index">P Entry</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SlnErp102.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.js"></script>
<script>
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>